### ISSUE TITLE
Flysystem Adapter Support

### ISSUE THREAD

**Issue by systemsolutionweb** [miqoo1996/google-drive#1]
Laravel uses [`flysystem`](https://github.com/thephpleague/flysystem/tree/1.x), if flysystem support is added, this package can be used on `filesystem.php`
https://github.com/thephpleague/flysystem/blob/1.x/src/AdapterInterface.php

**Comment by miqoo1996** [comment]
Hi @systemsolutionweb , that's a great suggestion, we're still working on improvements. If you think you can add it feel free making a PR and help us to improve the code in this matter.

Thanks a lot!
